# Generated by Django 5.1.2 on 2024-11-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
